### ISSUE TITLE
🚀 Feature: Implement any sorting algorithm of your choice

### ISSUE THREAD

**Issue by surya0180** [surya0180/Hacktoberfest2023#3]
## Sorting Algorithms

There are several sorting algorithms that can be used to sort some data structures. For starters, this issue aims to create a program which sorts an array of integers.

#### ⭐ Here are some beginner friendly algorithms that can be used to sort an array of integers
1. Quick Sort
2. Merge Sort
3. Bubble Sort
4. Selection Sort
5. Insertion Sort

🎯 Choose any programming language of your choice and implement any one of the algorithm mentioned above.
🎯 The program should take an array of integers as input from the users and print the sorted array as output.

**Comment by Thrivikramteja** [comment]
please assign this issue to me

**Comment by surya0180** [comment]
This issue is now assigned to you @Thrivikramteja

**Comment by Srishti2703** [comment]
Assign me this issue under hacktoberfest

**Comment by surya0180** [comment]
@Srishti2703 This is already assigned to another member.
