### ISSUE TITLE
Implement the Bellman-Ford Algorithm for Finding Shortest Paths

### ISSUE THREAD

**Issue by surya0180** [surya0180/Hacktoberfest2023#5]
This issue is dedicated to implementing the Bellman-Ford algorithm for finding the shortest paths in weighted graphs, including graphs that may contain negative-weight edges. The Bellman-Ford algorithm is a versatile graph algorithm that can be applied to various scenarios, such as network routing, financial modeling, and pathfinding.

The proposed changes for this issue include:

Implementing a Python function, say bellman_ford, that calculates the shortest paths from a specified source vertex to all other vertices in a weighted graph.
Ensuring that the function can handle graphs with negative-weight edges and correctly computes shortest paths.
Providing comprehensive documentation for the function, including examples and usage instructions.

The benefits of implementing this feature are as follows:

Enhanced graph analysis capabilities: Users can apply the Bellman-Ford algorithm to solve a wide range of problems, including those involving negative-weight edges.
Improved codebase: The addition of this graph algorithm enhances the project's versatility for solving real-world problems.

**Comment by Srishti2703** [comment]
Please assign this issue to me under hacktoberfest.

**Comment by surya0180** [comment]
I have assigned the issue to you
