### ISSUE TITLE
Implement a Hash Table Data Structure with Collision Handling

### ISSUE THREAD

**Issue by Srishti2703** [surya0180/Hacktoberfest2023#7]
This issue is focused on creating a hash table data structure in Python that can store key-value pairs and perform operations like adding, retrieving, and deleting items efficiently. Handling collisions is an essential consideration when implementing a hash table.

The proposed changes for this issue include:

Implementing a Python class, say HashTable, that represents a hash table.
Developing functions for adding key-value pairs, retrieving values by keys, and deleting key-value pairs.
Implementing a collision resolution strategy, such as chaining or open addressing.
Providing clear and concise documentation for the hash table, including examples and usage instructions.

The benefits of implementing this feature are as follows:

Efficient data storage: The hash table allows for quick retrieval of values using keys.
Versatile data structure: Users can apply the hash table for various data storage and retrieval tasks.

Please assign me this issue under hacktoberfest

**Comment by surya0180** [comment]
I have assigned this issue to you @Srishti2703

**Comment by surya0180** [comment]
This issue is now closed

**Comment by Srishti2703** [comment]
In hacktoberfest profile, It's showing "your PR/MR has not been accepted by a maintainer of the repository.....". Please help regarding this and do accept it under hacktoberfest 2023

**Comment by surya0180** [comment]
What about the remaining ones?

**Comment by Srishti2703** [comment]
Remaining ones PR with the label "hacktoberfest accepted" has been successfully submitted and are under 6 days review period

**Comment by surya0180** [comment]
Ok, I will add that label, But remember that creating many issues in a same repository or sending PRs too frequently may also lead to rejection of valid PRs. I suggest you to send a PR every 2 days to this repo so that you will be on the safer side.

**Comment by Srishti2703** [comment]
Okay

**Comment by Srishti2703** [comment]
Accept my recent one....From next time I'll be sending on every 2 days

**Comment by Srishti2703** [comment]
Okay...thankyou

**Comment by Srishti2703** [comment]
Hey @surya0180 Please label it as hacktoberfest-accepted
